from entities import Room, THIEF, TROLL, CYCLOPS, ROBOT
from objects import GameObject
from containers import Container
from typing import Optional, List, Dict
import glob


def load_rooms():
    rooms = {}
    # --- Canonical Zork room stubs (expand details as needed) ---
    canonical_rooms = [
        # House and surroundings
        "WHOUS",
        "NHOUS",
        "SHOUS",
        "EHOUS",
        "HOUSE",
        "KITCH",
        "LROOM",
        "ATTIC",
        # Forest and clearing
        "FORE1",
        "FORE2",
        "FORE3",
        "FORE4",
        "FORE5",
        "CLEAR",
        "TREE",
        # Cellar and underground
        "CELLAR",
        "CELLA",
        # Maze and dead ends
        "MAZE1",
        "MAZE2",
        "MAZE3",
        "MAZE4",
        "MAZE5",
        "MAZE6",
        "MAZE7",
        "MAZE8",
        "MAZE9",
        "MAZ10",
        "MAZ11",
        "MAZ12",
        "MAZ13",
        "MAZ14",
        "MAZ15",
        "DEAD1",
        "DEAD2",
        "DEAD3",
        "DEAD4",
        "DEAD5",
        "DEAD6",
        "DEAD7",
        # Special rooms
        "CYCLO",
        "TREAS",
        "TROLL",
        "BLROO",
        "GALLE",
        "STUDI",
        "MTROL",
        # Water and outdoors
        "RIVER",
        "FALLS",
        "BEACH",
        "POOL",
        "POND",
        "RESER",
        "RESEN",
        "RESERVOIR",
        "RESERVOIR-NORTH",
        "RESERVOIR-SOUTH",
        "RAVI1",
        "CRAW1",
        "RESES",
        "STREA",
        "INSTR",
        "EGYPT",
        "ICY",
        "RUBYR",
        "ATLAN",
        "CANY1",
        "ECHO",
        "MIRR1",
        "MIRR2",
        "CAVE1",
        "CAVE2",
        "CAVE3",
        "CAVE4",
        "CRAW2",
        "CRAW3",
        "CRAW4",
        "PASS3",
        "PASS4",
        "ENTRA",
        "SQUEE",
        "TSHAF",
        "TUNNE",
        "SMELL",
        "BOOM",
        "TLADD",
        "BLADD",
        "DEAD7",
        "TIMBE",
        "BSHAF",
        "MACHI",
        "BATS",
        "MINE1",
        "MINE2",
        "MINE3",
        "MINE4",
        "MINE5",
        "MINE6",
        "MINE7",
        "DOME",
        "MTORC",
        "CHAS2",
        "PASS1",
        "CAROU",
        "PASS5",
        "CHAS1",
        "CHAS3",
        "RIDDL",
        "MPEAR",
        "LLD1",
        "LLD2",
        "MGRAI",
        "TEMP1",
        "TEMP2",
        "DAM",
        "LOBBY",
        "MAINT",
        "DOCK",
        "RIVR1",
        "RIVR2",
        "RIVR3",
        "WCLF1",
        "WCLF2",
        "RIVR4",
        "RIVR5",
        "FCHMP",
        "FANTE",
        "RCAVE",
        "TCAVE",
        "RAINB",
        "POG",
        "CLBOT",
        "CLMID",
        "CLTOP",
        "VLBOT",
        "VAIR1",
        "VAIR2",
        "VAIR3",
        "VAIR4",
        "LEDG2",
        "LIBRA",
        "LEDG3",
        "LEDG4",
        "SAFE",
        "LAVA",
        "MAGNE",
        "CMACH",
        "CAGER",
        "CAGED",
        "TWELL",
        "BWELL",
        "ALICE",
        "ALISM",
        "ALITR",
        "BKENT",
        "BKTW",
        "BKTE",
        "BKVW",
        "BKVE",
        "BKTWI",
        "BKVAU",
        "BKBOX",
        "BKEXE",
        "CPANT",
        "CPOUT",
        "CP",
        "PALAN",
        "PRM",
        "SLIDE",
        "SLID1",
        "SLID2",
        "SLID3",
        "SLEDG",
        "SPAL",
        "MRD",
        "MRG",
        "MRC",
        "MRB",
        "MRA",
        "MRDE",
        "MRDW",
        "MRGE",
        "MRGW",
        "MRCE",
        "MRCW",
        "MRBE",
        "MRBW",
        "MRAE",
        "MRAW",
        "INMIR",
        "MRANT",
        "MREYE",
        "TOMB",
        "CRYPT",
        "TSTRS",
        "ECORR",
        "WCORR",
        "SCORR",
        "BDOOR",
        "FDOOR",
        "NCORR",
        "PARAP",
        "CELL",
        "PCELL",
        "NCELL",
        "NIRVA",
        # Magic, sound, and other
        "MAGNET-ROOM",
        "MIRROR-ROOM",
        "CAROUSEL-ROOM",
        "ECHO-ROOM",
        "SAFE-ROOM",
        "LOCKED-DOOR",
        "CELL-DOOR",
        # Add more as needed from canonical list...
    ]
    # Room flags mapping (expand as needed)
    room_flags = {
        "WHOUS": Room.ROOM_OUTDOORS,
        "FORE1": Room.ROOM_OUTDOORS,
        "FORE2": Room.ROOM_OUTDOORS,
        "FORE3": Room.ROOM_OUTDOORS,
        "FORE4": Room.ROOM_OUTDOORS,
        "FORE5": Room.ROOM_OUTDOORS,
        "CLEAR": Room.ROOM_OUTDOORS,
        "TREE": Room.ROOM_OUTDOORS,
        "BEACH": Room.ROOM_OUTDOORS,
        "CELLAR": Room.ROOM_DARK,
        "CELLA": Room.ROOM_DARK,
        "CYCLO": Room.ROOM_DARK | Room.ROOM_DEADLY,
        "TREAS": Room.ROOM_MAGIC,
        "TROLL": Room.ROOM_DEADLY,
        "ECHO": Room.ROOM_SOUND,
        "HOUSE": Room.ROOM_LOCKED,
        "LOCKED-DOOR": Room.ROOM_LOCKED,
        "CELL-DOOR": Room.ROOM_LOCKED,
        "SAFE-ROOM": Room.ROOM_LOCKED,
        # Add more as needed...
    }
    # Add canonical details for iconic rooms
    rooms["WHOUS"] = Room(
        id="WHOUS",
        desc_long="You are standing in an open field west of a white house, with a boarded front door. There is a small mailbox here.",
        desc_short="West of House",
        exits={"east": "HOUSE", "south": "FORE1", "north": "NHOUS", "west": "FORE3"},
        objects=[
            GameObject("Mailbox", "A small mailbox. It is closed.", attributes={"osize": 4, "open": False, "openable": True, "locked": False, "container": True, "takeable": False, "portable": False, "contents": [
                GameObject("Leaflet", "A leaflet. It reads: 'WELCOME TO ZORK!'")
            ]}),
        ],
        flags=Room.ROOM_OUTDOORS,
        action=None,
        npcs=[],
    )
    rooms["NHOUS"] = Room(
        id="NHOUS",
        desc_long="You are facing the north side of a white house. There is no door here, and all the windows are barred.",
        desc_short="North of House",
        exits={"south": "WHOUS", "east": "FORE2"},
        objects=[],
        flags=Room.ROOM_OUTDOORS,
        action=None,
        npcs=[],
    )
    rooms["SHOUS"] = Room(
        id="SHOUS",
        desc_long="You are facing the south side of a white house. There is no door here, and all the windows are barred.",
        desc_short="South of House",
        exits={"north": "WHOUS", "east": "FORE4"},
        objects=[],
        flags=Room.ROOM_OUTDOORS,
        action=None,
        npcs=[],
    )
    rooms["EHOUS"] = Room(
        id="EHOUS",
        desc_long="You are behind the white house. In one corner of the house there is a small window which is closed.",
        desc_short="Behind House",
        exits={"west": "HOUSE", "south": "FORE5"},
        objects=[
            GameObject("Window", "A small window. It is closed.", attributes={"osize": 2, "openable": True, "open": False, "takeable": False, "portable": False}),
        ],
        flags=Room.ROOM_OUTDOORS,
        action=None,
        npcs=[],
    )
    rooms["HOUSE"] = Room(
        id="HOUSE",
        desc_long="You are inside the white house. There is a door to the west and a staircase leading up. A passage leads east into the living room, and a dark staircase can be seen leading downward. The kitchen is to the north.",
        desc_short="Inside House",
        exits={"west": "WHOUS", "up": "ATTIC", "east": "LROOM", "down": "CELLAR", "north": "KITCH"},
        objects=[
            GameObject("Table", "A wooden table stands here.", attributes={"osize": 8, "takeable": False, "portable": False, "surface": True}),
        ],
        flags=Room.ROOM_LOCKED,
        action=None,
        npcs=[],
    )
    rooms["KITCH"] = Room(
        id="KITCH",
        desc_long="You are in the kitchen. A table seems to have been used recently for the preparation of food. A passage leads to the west and a dark staircase can be seen leading downward. A refrigerator is to one side of the room. On the table is a brass lantern. A brown sack is here."
        ,
        desc_short="Kitchen",
        exits={"west": "HOUSE", "down": "CELLAR"},
        objects=[
            GameObject("Lantern", "A brass lantern.", attributes={"osize": 2, "takeable": True, "portable": True}),
            GameObject("Refrigerator", "A refrigerator. It is closed.", attributes={"osize": 10, "openable": True, "open": False, "container": True, "takeable": False, "portable": False}),
            GameObject("Sack", "A brown sack.", attributes={"osize": 1, "takeable": True, "portable": True, "container": True, "open": True, "openable": True, "contents": [
                GameObject("Lunch", "A tasty lunch.", attributes={"osize": 1, "takeable": True, "portable": True}),
                GameObject("Water Bottle", "A bottle of water.", attributes={"osize": 1, "takeable": True, "portable": True}),
            ]}),
        ],
        flags=0,
        action=None,
        npcs=[],
    )
    rooms["LROOM"] = Room(
        id="LROOM",
        desc_long="You are in the living room. There is a trophy case and a large oriental rug in the center of the room. Above the trophy case hangs an elvish sword of great antiquity. A battery-powered brass lamp is on the trophy case. The door to the east leads back outside.",
        desc_short="Living Room",
        exits={"east": "HOUSE"},
        objects=[
            GameObject("Trophy Case", "A trophy case.", attributes={"osize": 8, "openable": True, "open": False, "container": True, "takeable": False, "portable": False}),
            GameObject("Rug", "A large oriental rug.", attributes={"osize": 10, "takeable": False, "portable": False}),
            GameObject("Sword", "An elvish sword of great antiquity.", attributes={"osize": 2, "takeable": True, "portable": True, "weapon": True}),
            GameObject("Lamp", "A battery-powered brass lamp.", attributes={"osize": 1, "takeable": True, "portable": True}),
        ],
        flags=0,
        action=None,
        npcs=[],
    )
    rooms["ATTIC"] = Room(
        id="ATTIC",
        desc_long="You are in the attic. The only exit is a stairway leading down.",
        desc_short="Attic",
        exits={"down": "HOUSE"},
        objects=[],
        flags=0,
        action=None,
        npcs=[],
    )
    rooms["KITCH"] = Room(
        id="KITCH",
        desc_long="You are in the kitchen. A table seems to have been used recently for the preparation of food. A passage leads to the west and a dark staircase can be seen leading downward. A refrigerator is to one side of the room. On the table is a brass lantern."
        ,
        desc_short="Kitchen",
        exits={"west": "HOUSE", "down": "CELLAR"},
        objects=[
            GameObject("Lantern", "A brass lantern.", attributes={"osize": 2, "takeable": True, "portable": True}),
            GameObject("Refrigerator", "A refrigerator. It is closed.", attributes={"osize": 10, "openable": True, "open": False, "container": True, "takeable": False, "portable": False}),
        ],
        flags=0,
        action=None,
        npcs=[],
    )
    rooms["LROOM"] = Room(
        id="LROOM",
        desc_long="You are in the living room. There is a trophy case and a large oriental rug in the center of the room. Above the trophy case hangs an elvish sword of great antiquity. A battery-powered brass lamp is on the trophy case. The door to the east leads back outside.",
        desc_short="Living Room",
        exits={"east": "HOUSE"},
        objects=[
            GameObject("Trophy Case", "A trophy case.", attributes={"osize": 8, "openable": True, "open": False, "container": True, "takeable": False, "portable": False}),
            GameObject("Rug", "A large oriental rug.", attributes={"osize": 10, "takeable": False, "portable": False}),
            GameObject("Sword", "An elvish sword of great antiquity.", attributes={"osize": 2, "takeable": True, "portable": True, "weapon": True}),
            GameObject("Lamp", "A battery-powered brass lamp.", attributes={"osize": 1, "takeable": True, "portable": True}),
        ],
        flags=0,
        action=None,
        npcs=[],
    )
    rooms["CELLAR"] = Room(
        id="CELLAR",
        desc_long="You are in a dark, damp cellar. The smell of mold fills the air. There are stairs leading up. A passage leads south, and a crawlway leads west.",
        desc_short="Cellar",
        exits={"up": "KITCH", "south": "TROLL", "west": "STUDI"},
        objects=[
            GameObject("Bottle", "A dusty old wine bottle.", attributes={"osize": 1, "score_value": 2, "takeable": True, "portable": True}),
        ],
        flags=Room.ROOM_DARK,
        action=None,
        npcs=[],
    )
    rooms["CYCLO"] = Room(
        id="CYCLO",
        desc_long="A huge cyclops glares at you, hungry and irritable. The only exit is down a narrow stairway.",
        desc_short="Cyclops Room",
        exits={"down": "TROLL"},
        objects=[],
        flags=Room.ROOM_DARK | Room.ROOM_DEADLY,
        action=None,
        npcs=[CYCLOPS],
    )
    rooms["TREAS"] = Room(
        id="TREAS",
        desc_long="The Treasure Room sparkles with loot. A sneaky thief lurks here, eyeing your valuables.",
        desc_short="Treasure Room",
        exits={"west": "CYCLO"},
        objects=[
            GameObject("Chalice", "A golden chalice encrusted with gems.", attributes={"osize": 2, "score_value": 25, "takeable": True, "portable": True}),
        ],
        flags=Room.ROOM_MAGIC,
        action=None,
        npcs=[THIEF],
    )
    rooms["TROLL"] = Room(
        id="TROLL",
        desc_long="A menacing troll blocks the bridge, demanding payment. The only exits are north and south.",
        desc_short="Troll Room",
        exits={"north": "BRIDGE", "south": "CELLA"},
        objects=[
            GameObject("Axe", "A heavy troll's axe.", attributes={"osize": 5, "takeable": True, "portable": True, "weapon": True}),
        ],
        flags=Room.ROOM_DEADLY,
        action=None,
        npcs=[TROLL],
    )
    # All other rooms as stubs
    for r in canonical_rooms:
        if r not in rooms:
            rooms[r] = Room(
                id=r,
                desc_long=f"[Stub] {r} (add canonical description)",
                desc_short=r,
                exits={},
                objects=[],
                flags=room_flags.get(r, 0),
                action=None,
                npcs=[],
            )
    return rooms
