from entities import Room, THIEF, TROLL, CYCLOPS, ROBOT
from objects import GameObject
from containers import Container
from typing import Optional, List, Dict
import glob


def load_rooms():
    rooms = {}
    # --- Canonical Zork room stubs (expand details as needed) ---
    canonical_rooms = [
        # House and surroundings
        "WHOUS",
        "NHOUS",
        "SHOUS",
        "EHOUS",
        "HOUSE",
        "KITCH",
        "LROOM",
        "ATTIC",
        # Forest and clearing
        "FORE1",
        "FORE2",
        "FORE3",
        "FORE4",
        "FORE5",
        "CLEAR",
        "TREE",
        # Cellar and underground
        "CELLAR",
        "CELLA",
        # Maze and dead ends
        "MAZE1",
        "MAZE2",
        "MAZE3",
        "MAZE4",
        "MAZE5",
        "MAZE6",
        "MAZE7",
        "MAZE8",
        "MAZE9",
        "MAZ10",
        "MAZ11",
        "MAZ12",
        "MAZ13",
        "MAZ14",
        "MAZ15",
        "DEAD1",
        "DEAD2",
        "DEAD3",
        "DEAD4",
        "DEAD5",
        "DEAD6",
        "DEAD7",
        # Special rooms
        "CYCLO",
        "TREAS",
        "TROLL",
        "BLROO",
        "GALLE",
        "STUDI",
        "MTROL",
        # Water and outdoors
        "RIVER",
        "FALLS",
        "BEACH",
        "POOL",
        "POND",
        "RESER",
        "RESEN",
        "RESERVOIR",
        "RESERVOIR-NORTH",
        "RESERVOIR-SOUTH",
        "RAVI1",
        "CRAW1",
        "RESES",
        "STREA",
        "INSTR",
        "EGYPT",
        "ICY",
        "RUBYR",
        "ATLAN",
        "CANY1",
        "ECHO",
        "MIRR1",
        "MIRR2",
        "CAVE1",
        "CAVE2",
        "CAVE3",
        "CAVE4",
        "CRAW2",
        "CRAW3",
        "CRAW4",
        "PASS3",
        "PASS4",
        "ENTRA",
        "SQUEE",
        "TSHAF",
        "TUNNE",
        "SMELL",
        "BOOM",
        "TLADD",
        "BLADD",
        "DEAD7",
        "TIMBE",
        "BSHAF",
        "MACHI",
        "BATS",
        "MINE1",
        "MINE2",
        "MINE3",
        "MINE4",
        "MINE5",
        "MINE6",
        "MINE7",
        "DOME",
        "MTORC",
        "CHAS2",
        "PASS1",
        "CAROU",
        "PASS5",
        "CHAS1",
        "CHAS3",
        "RIDDL",
        "MPEAR",
        "LLD1",
        "LLD2",
        "MGRAI",
        "TEMP1",
        "TEMP2",
        "DAM",
        "LOBBY",
        "MAINT",
        "DOCK",
        "RIVR1",
        "RIVR2",
        "RIVR3",
        "WCLF1",
        "WCLF2",
        "RIVR4",
        "RIVR5",
        "FCHMP",
        "FANTE",
        "RCAVE",
        "TCAVE",
        "RAINB",
        "POG",
        "CLBOT",
        "CLMID",
        "CLTOP",
        "VLBOT",
        "VAIR1",
        "VAIR2",
        "VAIR3",
        "VAIR4",
        "LEDG2",
        "LIBRA",
        "LEDG3",
        "LEDG4",
        "SAFE",
        "LAVA",
        "MAGNE",
        "CMACH",
        "CAGER",
        "CAGED",
        "TWELL",
        "BWELL",
        "ALICE",
        "ALISM",
        "ALITR",
        "BKENT",
        "BKTW",
        "BKTE",
        "BKVW",
        "BKVE",
        "BKTWI",
        "BKVAU",
        "BKBOX",
        "BKEXE",
        "CPANT",
        "CPOUT",
        "CP",
        "PALAN",
        "PRM",
        "SLIDE",
        "SLID1",
        "SLID2",
        "SLID3",
        "SLEDG",
        "SPAL",
        "MRD",
        "MRG",
        "MRC",
        "MRB",
        "MRA",
        "MRDE",
        "MRDW",
        "MRGE",
        "MRGW",
        "MRCE",
        "MRCW",
        "MRBE",
        "MRBW",
        "MRAE",
        "MRAW",
        "INMIR",
        "MRANT",
        "MREYE",
        "TOMB",
        "CRYPT",
        "TSTRS",
        "ECORR",
        "WCORR",
        "SCORR",
        "BDOOR",
        "FDOOR",
        "NCORR",
        "PARAP",
        "CELL",
        "PCELL",
        "NCELL",
        "NIRVA",
        # Magic, sound, and other
        "MAGNET-ROOM",
        "MIRROR-ROOM",
        "CAROUSEL-ROOM",
        "ECHO-ROOM",
        "SAFE-ROOM",
        "LOCKED-DOOR",
        "CELL-DOOR",
        # Add more as needed from canonical list...
    ]
    # Room flags mapping (expand as needed)
    room_flags = {
        "WHOUS": Room.ROOM_OUTDOORS,
        "FORE1": Room.ROOM_OUTDOORS,
        "FORE2": Room.ROOM_OUTDOORS,
        "FORE3": Room.ROOM_OUTDOORS,
        "FORE4": Room.ROOM_OUTDOORS,
        "FORE5": Room.ROOM_OUTDOORS,
        "CLEAR": Room.ROOM_OUTDOORS,
        "TREE": Room.ROOM_OUTDOORS,
        "BEACH": Room.ROOM_OUTDOORS,
        "CELLAR": Room.ROOM_DARK,
        "CELLA": Room.ROOM_DARK,
        "CYCLO": Room.ROOM_DARK | Room.ROOM_DEADLY,
        "TREAS": Room.ROOM_MAGIC,
        "TROLL": Room.ROOM_DEADLY,
        "ECHO": Room.ROOM_SOUND,
        "HOUSE": Room.ROOM_LOCKED,
        "LOCKED-DOOR": Room.ROOM_LOCKED,
        "CELL-DOOR": Room.ROOM_LOCKED,
        "SAFE-ROOM": Room.ROOM_LOCKED,
        # Add more as needed...
    }
    # Add all canonical rooms as stubs if not already defined
    for r in canonical_rooms:
        if r not in rooms:
            rooms[r] = Room(
                id=r,
                desc_long=f"[Stub] {r} (add canonical description)",
                desc_short=r,
                exits={},
                objects=[],
                flags=room_flags.get(r, 0),
                action=None,
                npcs=[],
            )
    # Example: add a canonical object to CELLAR
    if "CELLAR" in rooms:
        rooms["CELLAR"].objects.append(
            GameObject(
                "Bottle",
                "A dusty old wine bottle.",
                attributes={
                    "osize": 1,
                    "score_value": 2,
                    "takeable": True,
                    "portable": True,
                },
            )
        )
    return rooms
