from main import Room

# Auto-generated room definitions from map.json

def create_rooms():
    rooms = {}
    room_names = [
        "DPR", "TOMB-FUNCTION", "START-END", "MIRBLOCK", "GO-E-W", "MRCEW", "MRBEW", "MRAEW", "MRDF", "MRCF", "MRBF", "MRAF", "GUARDIANS", "MIRROR-HERE", "MIRIN", "MRSWITCH", "MPANELS", "SHORT-POLE", "MASTER-FUNCTION", "BDOOR-FUNCTION", "FDOOR-FUNCTION", "WOOD-DOOR", "STAY", "STUFF", "PARAPET", "TAKE-FIVE", "CELL-ROOM", "PCELL-ROOM", "NCELL-ROOM", "NCORR-ROOM", "SCORR-ROOM", "CELL-DOOR", "MAYBE-DOOR", "LOCKED-DOOR", "NIRVANA", "TURNTO", "OFF-APPLY", "BATS-ROOM", "MACHINE-ROOM", "NO-OBJS", "CLIFF-FUNCTION", "STICK-FUNCTION", "FALLS-ROOM", "DBOAT-FUNCTION", "OVER-FALLS", "SHAKER", "DIGGER", "GROUND-FUNCTION", "SAND-FUNCTION", "GUANO-FUNCTION", "GERONIMO", "GRUE-FUNCTION", "PUT-BALLOON", "BCONTENTS", "WIRE-FUNCTION", "SAFE-ROOM", "SAFE-FUNCTION", "BRICK-FUNCTION", "SAFE-MUNG", "LEDGE-MUNG", "LEDGE-FUNCTION", "BLAST", "VOLGNOME", "GNOME-FUNCTION", "COKE-BOTTLES", "EATME-FUNCTION", "FLASK-FUNCTION", "PLEAK", "MAGNET-ROOM", "CMACH-ROOM", "BUTTONS", "CAGED-ROOM", "ROBOT-ACTOR", "CRETIN", "ROBOT-FUNCTION", "KNOCK", "BKLEAVEE", "TELLER-ROOM", "ZGNOME-INIT", "ZGNOME-FUNCTION", "WIND", "CANARY-OBJECT", "FOREST-ROOM", "BIRD-OBJECT", "WCLIF-OBJECT", "CPENTER", "CPANT-ROOM", "CP-ROOM", "CPSLT-OBJECT", "CPOUT-ROOM", "PKH-FUNCTION", "PLID-FUNCTION", "PWIND-FUNCTION", "PDOOR-FUNCTION", "PKEY-FUNCTION", "PUT-UNDER", "SLIDE-EXIT", "SLIDE-CINT", "UNTIE-FROM", "SLIDE-ROPE", "TIMBERS", "SLIDE-FUNCTION", "SLIDER", "SLEDG-ROOM", "STOVE-FUNCTION", "SRNAME", "PLAY", "MAKER", "WELL-FUNCTION", "SENDER", "BROCHURE", "NUMTELL", "GET-SRUV", "BLO", "ILO", "EAST-HOUSE", "OPEN-CLOSE", "KITCHEN", "TROPHY-CASE", "TRAP-DOOR", "CELLAR", "RUG", "AXE-FUNCTION", "LEAVES-APPEAR", "LEAF-PILE", "HOUSE-FUNCTION", "MAZE-11", "GRATE-FUNCTION", "RUSTY-KNIFE", "GLACIER", "GLACIER-ROOM", "TORCH-OBJECT", "MIRROR-ROOM", "CAROUSEL-ROOM", "CAROUSEL-EXIT", "TORCH-ROOM", "DOME-ROOM", "COFFIN-CURE", "POUR-ON", "LLD2-ROOM", "GHOST-FUNCTION", "DAM-ROOM", "SQUEEZER", "OIL", "DBUTTONS", "TOOL-CHEST", "LEAK-FUNCTION", "TUBE-FUNCTION", "RESERVOIR-SOUTH", "RESERVOIR", "RESERVOIR-NORTH", "BOTTLE-FUNCTION", "FILL", "CYCLOPS-ROOM", "AOS-SOS", "CHALICE", "THIEF-IN-TREASURE", "TREAS", "SINBAD", "GRANITE", "BRUSH", "RING", "PRAYER", "HELLO", "READER", "LOOK-INSIDE", "LOOK-UNDER", "BURNER", "TURNER", "DDOOR-FUNCTION", "PUMPER", "INFLATER", "DEFLATER", "LOCKER", "UNLOCKER", "KILLER", "MUNGER", "EXORCISE", "PLUGGER", "UNTIE", "PUSHER", "TIE", "TIE-UP", "MELTER", "ALARM", "BODY-FUNCTION", "BLACK-BOOK", "PAINTING", "SWORD", "MSETG", "DISP-FROB", "CURE-CLOCK", "FIND-VERB", "FIND-DIR", "FIND-ACTION", "COLUMN", "PVBIT", "SNARF-OBJECT", "SPLICE-OUT", "DC", "NO-OBJ-HACK", "SCORE-OBJ", "SCORE-ROOM", "SCORE-UPD", "SCORE-BLESS", "OPENER", "CLOSER", "FIND", "MOVE", "LAMP-OFF", "SELECT-SOME", "FIND-PREP", "ADD-DEMON", "ZPRINT", "ZIN", "ZEQUALS", "ZIF", "ZFOR-EACH", "ZPLUS", "ZMINUS", "ZTIMES", "ZDIVIDED", "ZLESS", "ZGREATER", "ZEQUAL", "ZAND", "ZOR", "ZCONTENTS", "ZSET", "ZDEFINE", "ZLOAD", "ZDUMP", "ZINT-FIND", "ZTAKE", "ZREMOVE", "ZPUTIN", "ZGOTO", "ZRETRY", "ZCREATE"
    ]
    for name in room_names:
        rooms[name] = Room(
            id=name,
            desc_long=f"This is the {name} room/location.",
            desc_short=f"{name}.",
            exits={},
            objects=[],
            flags=[],
            action=None
        )
    return rooms
